src/Entity/Jobs.php
<?php

namespace App\Entity;

use App\Repository\JobsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=JobsRepository::class)
 */
class Jobs
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hours;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $salary;

    /**
     * @ORM\Column(type="boolean")
     */
    private $validated;

    /**
     * @ORM\Column(type="boolean")
     */
    private $published;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="jobsCreated")
     * @ORM\JoinColumn(nullable=false)
     */
    private $createdBy;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="jobsChecked")
     */
    private $checkedBy;

    /**
     * @ORM\ManyToMany(targetEntity=Users::class, inversedBy="jobsPostulated")
     */
    private $Candidates;

    public function __construct()
    {
        $this->Candidates = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getHours(): ?string
    {
        return $this->hours;
    }

    public function setHours(string $hours): self
    {
        $this->hours = $hours;

        return $this;
    }

    public function getSalary(): ?string
    {
        return $this->salary;
    }

    public function setSalary(string $salary): self
    {
        $this->salary = $salary;

        return $this;
    }

    public function getValidated(): ?bool
    {
        return $this->validated;
    }

    public function setValidated(bool $validated): self
    {
        $this->validated = $validated;

        return $this;
    }

    public function getPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): self
    {
        $this->published = $published;

        return $this;
    }

    public function getCreatedBy(): ?Users
    {
        return $this->createdBy;
    }

    public function setCreatedBy(?Users $createdBy): self
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function getCheckedBy(): ?Users
    {
        return $this->checkedBy;
    }

    public function setCheckedBy(?Users $checkedBy): self
    {
        $this->checkedBy = $checkedBy;

        return $this;
    }

    /**
     * @return Collection|Users[]
     */
    public function getCandidates(): Collection
    {
        return $this->Candidates;
    }

    public function addCandidate(Users $candidate): self
    {
        if (!$this->Candidates->contains($candidate)) {
            $this->Candidates[] = $candidate;
        }

        return $this;
    }

    public function removeCandidate(Users $candidate): self
    {
        $this->Candidates->removeElement($candidate);

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\ManyToOne(targetEntity=Companies::class, inversedBy="users")
     */
    private $company;

    /**
     * @ORM\OneToMany(targetEntity=Jobs::class, mappedBy="createdBy", orphanRemoval=true)
     */
    private $jobsCreated;

    /**
     * @ORM\OneToMany(targetEntity=Jobs::class, mappedBy="checkedBy")
     */
    private $jobsChecked;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Validated;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="usersValidated")
     */
    private $ValidatedBy;

    /**
     * @ORM\OneToMany(targetEntity=Users::class, mappedBy="ValidatedBy")
     */
    private $usersValidated;

    /**
     * @ORM\ManyToMany(targetEntity=Jobs::class, mappedBy="Candidates")
     */
    private $jobsPostulated;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cv;


    public function __construct()
    {
        $this->jobsCreated = new ArrayCollection();
        $this->jobsChecked = new ArrayCollection();
        $this->usersValidated = new ArrayCollection();
        $this->jobsPostulated = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getCompany(): ?Companies
    {
        return $this->company;
    }

    public function setCompany(?Companies $company): self
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return Collection|Jobs[]
     */
    public function getJobsCreated(): Collection
    {
        return $this->jobsCreated;
    }

    public function addJobsCreated(Jobs $jobsCreated): self
    {
        if (!$this->jobsCreated->contains($jobsCreated)) {
            $this->jobsCreated[] = $jobsCreated;
            $jobsCreated->setCreatedBy($this);
        }

        return $this;
    }

    public function removeJobsCreated(Jobs $jobsCreated): self
    {
        if ($this->jobsCreated->removeElement($jobsCreated)) {
            // set the owning side to null (unless already changed)
            if ($jobsCreated->getCreatedBy() === $this) {
                $jobsCreated->setCreatedBy(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Jobs[]
     */
    public function getJobsChecked(): Collection
    {
        return $this->jobsChecked;
    }

    public function addJobsChecked(Jobs $jobsChecked): self
    {
        if (!$this->jobsChecked->contains($jobsChecked)) {
            $this->jobsChecked[] = $jobsChecked;
            $jobsChecked->setCheckedBy($this);
        }

        return $this;
    }

    public function removeJobsChecked(Jobs $jobsChecked): self
    {
        if ($this->jobsChecked->removeElement($jobsChecked)) {
            // set the owning side to null (unless already changed)
            if ($jobsChecked->getCheckedBy() === $this) {
                $jobsChecked->setCheckedBy(null);
            }
        }

        return $this;
    }

    public function getValidated(): ?bool
    {
        return $this->Validated;
    }

    public function setValidated(bool $Validated): self
    {
        $this->Validated = $Validated;

        return $this;
    }

    public function getValidatedBy(): ?self
    {
        return $this->ValidatedBy;
    }

    public function setValidatedBy(?self $ValidatedBy): self
    {
        $this->ValidatedBy = $ValidatedBy;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getUsersValidated(): Collection
    {
        return $this->usersValidated;
    }

    public function addUsersValidated(self $usersValidated): self
    {
        if (!$this->usersValidated->contains($usersValidated)) {
            $this->usersValidated[] = $usersValidated;
            $usersValidated->setValidatedBy($this);
        }

        return $this;
    }

    public function removeUsersValidated(self $usersValidated): self
    {
        if ($this->usersValidated->removeElement($usersValidated)) {
            // set the owning side to null (unless already changed)
            if ($usersValidated->getValidatedBy() === $this) {
                $usersValidated->setValidatedBy(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Jobs[]
     */
    public function getJobsPostulated(): Collection
    {
        return $this->jobsPostulated;
    }

    public function addJobsPostulated(Jobs $jobsPostulated): self
    {
        if (!$this->jobsPostulated->contains($jobsPostulated)) {
            $this->jobsPostulated[] = $jobsPostulated;
            $jobsPostulated->addCandidate($this);
        }

        return $this;
    }

    public function removeJobsPostulated(Jobs $jobsPostulated): self
    {
        if ($this->jobsPostulated->removeElement($jobsPostulated)) {
            $jobsPostulated->removeCandidate($this);
        }

        return $this;
    }

    public function getCv(): ?string
    {
        return $this->cv;
    }

    public function setCv(?string $cv): self
    {
        $this->cv = $cv;

        return $this;
    }
}

templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos offres d'emploi!{% endblock %}

{% block body %}
    <div>
        <nav class="navbar navbar-light bg-light">
            <div class="container-fluid justify-content-center">
                <form class="d-flex" action="{{ path('home') }}">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
                    <button class="btn btn-outline-success" type="submit" >Search</button>
                </form>
            </div>
        </nav>
    </div>
    <div class="d-flex flex-row row">
        {% for job in jobs %}
            <div class="col-2">
                <div class="card m-3" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{ job.title }}</h5>
                        <p class="card-text">{{ job.description }}</p>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target='#modal{{ job.id }}'>
                            En savoir plus
                        </button>
                    </div>
                </div>
            </div>


            <!-- Modal -->
            <div class="modal fade" id='modal{{ job.id }}' tabindex="-1" aria-labelledby="jobModal" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title text-info" id="jobModalLabel">{{ job.getCreatedBy.getCompany.name }} vous propose ce poste:</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            {% block showJobModal %}
                                {% include 'jobs/showModal.html.twig' %}
                            {% endblock showJobModal %}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            {% if user is not null %}
                                {% set alreadyPostulated = 'false' %}
                                {% for candidate in job.candidates %}
                                    {% if candidate.email == user.userIdentifier %}
                                        <p class="text-warning">déjà postulé!</p>
                                        {% set alreadyPostulated = 'true' %}
                                    {% endif %}
                                {% endfor %}
                                {% if alreadyPostulated == 'false'%}
                                    {% set userRole = 'ROLE_USER' %}
                                    {% for role in user.roles %}
                                        {% if role == "ROLE_CONSULTANT" or role == "ROLE_RECRUITER" or role == "ROLE_ADMIN"%}
                                            {% set userRole = 'OTHER_ROLE' %}
                                        {% endif %}
                                    {%endfor %}
                                    {% if userRole == 'ROLE_USER' %}
                                        <button type="button" class="btn btn-primary postulatedButton" jobId={{ job.id }} user=1 validatedUser="{{ user.getValidated }}">Je postule</button>
                                    {% endif %}
                                {% endif %}
                            {% else %}
                                <button type="button" class="btn btn-primary postulatedButton" jobId={{ job.id }} user=0>Je postule</button>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/pages/userhome.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace utilisateur{% endblock %}

{% block body %}
    <div class="example-wrapper mx-2">
        <h2 class="text-dark mt-3">Bonjour {{ user.getFirstname }},</h2>
        <p class="text-secondary fw-bold mt-5">Votre compte</p>
        <div class="bg-light border border-primary border-3 w-25 pb-3 mx-2">
            {% include 'users/show.html.twig' %}
        </div>
        {% for role in user.roles %}
            {% if role == "ROLE_ADMIN" %}
                <div class="mt-5 mx-3"><a href="{{ path('admin_index') }}">Liste des utilisateurs</a></div>
            {% endif %}
        {% endfor %}
        {% for role in user.roles %}
            {# Recruiter can add a job if his account is validated and he added his company informations #}
            {% if role == "ROLE_RECRUITER" and user.getValidated == 1 and user.getCompany is not null %}
                <div class="mt-5"><a href="{{ path('jobs_index') }}">Voir la liste des emplois que vous avez publiés</a></div>
                <div class="mt-5"><a href="{{ path('jobs_new') }}">Ajouter une offre d'emploi</a></div>
                <div class="d-flex">
                    {# add all candidacies which are validated #}
                    <div class="mt-5 text-primary"> Candidatures validées: </div>
                    {% for postulatedJob in postulatedJobsToValidate %}
                        {% if postulatedJob.validated == 1 %}
                            <div class="w-25 table">
                                {% include 'jobs/postulatedJob.html.twig' %}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        {% endfor %}
        {# add all postulated jobs (only ROLE_USER can postulate) #}
        {% if user.roles|length < 2 %}
            <div class="mt-5 text-secondary">Vous avez postulé à ces offres d'emploi: </div>
            {% for job in jobsPostulated %}
                <div><a class="nav-link" href="{{ path('jobs_show', {'id': job.id}) }}">{{ job.title }}</a></div>
            {% endfor %}
        {% endif %}
        {# For consultant: add accounts, jobs and candidacies to validate #}
        {% for role in user.roles %}
            {% if role == "ROLE_CONSULTANT" %}
                <div class="d-flex">
                    <div class="mt-5 text-secondary">Comptes à valider: </div>
                    {% for user in users %}
                        {% set userRole = "ROLE_USER" %}
                        {% for role in user.roles %}
                            {% if role == "ROLE_RECRUITER" %}
                                {% set userRole = "ROLE_RECRUITER" %}
                            {% endif %}
                            {% if role == "ROLE_ADMIN" or role == "ROLE_CONSULTANT" %}
                                {% set userRole = "ROLE_OTHER" %}
                            {% endif %}
                        {% endfor %}
                        {# We have to show all accounts to validate except consultant and admin accounts #}
                        {% if user.validatedBy is null and userRole != "ROLE_OTHER" %}
                            <div class="w-25 table mx-3">
                                {% include 'users/toValidate.html.twig' %}
                                <div class="mx-3">
                                    {% if userRole == 'ROLE_RECRUITER' %}
                                        {% if user.company is not null %}
                                            <p class="text-danger">RECRUTEUR</p>
                                            <span class="fw-bold">{{ user.company.name }}</span> - {{ user.company.address }}
                                        {% endif%}
                                    {% endif %}
                                </div>
                                <div class="mx-3">
                                    <a class="btn btn-success" href="{{ path('users_validate',{'id': user.id}) }}">Valider</a>
                                    <a class="btn btn-danger" href="{{ path('users_reject',{'id': user.id}) }}">Rejeter</a>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="d-flex">
                    <div class="mt-5 text-secondary"> Offres d'emploi à valider: </div>
                    {% for job in jobs %}
                        {% if job.checkedBy is null %}
                            <div class="w-25 table">
                                {% include 'jobs/toValidate.html.twig' %}
                                <div class="mx-3">
                                    <a class="btn btn-success" href="{{ path('jobs_validate',{'id': job.id}) }}">Valider</a>
                                    <a class="btn btn-danger" href="{{ path('jobs_reject',{'id': job.id}) }}">Rejeter</a>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="d-flex">
                    <div class="mt-5 text-secondary"> candidatures à valider: </div>
                    {% for postulatedJob in postulatedJobsToValidate %}
                        {% if postulatedJob.checkedBy is null %}
                            <div class="w-25 table">
                                {% include 'jobs/postulatedJob.html.twig' %}
                                <div class="mx-3">
                                    <a class="btn btn-success" href="{{ path('PostulatedJob_validate',{'id': postulatedJob.id}) }}">Valider</a>
                                    <a class="btn btn-danger" href="{{ path('PostulatedJob_reject',{'id': postulatedJob.id}) }}">Rejeter</a>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        {%endfor %}
    </div>
{% endblock %}